name: Apply Global
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/global/**
env:
  SHARED_ACTIONS_REF: v1
  SERVICE_NAME: {{ cookiecutter.project_slug }}
{%- raw %}
jobs:
  apply_global:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: elationemr/services-shared
          ref: ${{ env.SHARED_ACTIONS_REF }}
          token: ${{ secrets.AUTOMATION_USER_PAT }}
          path: ./.github/shared
      - name: Apply Global
        uses: ./.github/shared/github/service/actions/apply_global
        with:
          service_name: ${{ env.SERVICE_NAME }}
          terraform_token: ${{ secrets.TF_API_TOKEN }}
          terraform_modules_ssh_key: ${{ secrets.TF_MODULES_SSH_KEY }}
{%- endraw %}
