name: Terraform Format
on:
  pull_request:
    paths:
      - terraform/**

{%- raw %}
jobs:
  terraform-format:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Format
        uses: elationemr/github-actions/terraform/fmt@main
        with:
          terraform_version: 1.3.9
          recursive: true
{%- endraw %}
