default_language_version:
  python: python3.10
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [file, python]
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run pytest --cov app --cov-report xml --cov-report term --cov-fail-under=85
        pass_filenames: false
        language: system
